//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emignatik.NxFileViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emignatik.NxFileViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load settings: {0}.
        /// </summary>
        public static string AppSettingsLoadingFailed {
            get {
                return ResourceManager.GetString("AppSettingsLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string AppType {
            get {
                return ResourceManager.GetString("AppType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string AvailableLanguages {
            get {
                return ResourceManager.GetString("AvailableLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content {0}.
        /// </summary>
        public static string ContentNum {
            get {
                return ResourceManager.GetString("ContentNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt NCA header(s)....
        /// </summary>
        public static string DecryptSelectedNcaFilesHeader {
            get {
                return ResourceManager.GetString("DecryptSelectedNcaFilesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Version.
        /// </summary>
        public static string DisplayVersion {
            get {
                return ResourceManager.GetString("DisplayVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Type.
        /// </summary>
        public static string DistributionType {
            get {
                return ResourceManager.GetString("DistributionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file &quot;{0}&quot;..
        /// </summary>
        public static string ErrFailedToLoadFile {
            get {
                return ResourceManager.GetString("ErrFailedToLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys file path defined in the settings &quot;{0}&quot; couldn&apos;t be found..
        /// </summary>
        public static string ErrKeysFilePathNotFound {
            get {
                return ResourceManager.GetString("ErrKeysFilePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys file path defined in the settings is empty..
        /// </summary>
        public static string ErrKeysFilePathUndefined {
            get {
                return ResourceManager.GetString("ErrKeysFilePathUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load keys from file &quot;{0}&quot;: {1}..
        /// </summary>
        public static string ErrKeysLoadingFailed {
            get {
                return ResourceManager.GetString("ErrKeysLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Info.
        /// </summary>
        public static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys successfully loaded..
        /// </summary>
        public static string InfoKeysSuccessfullyLoaded {
            get {
                return ResourceManager.GetString("InfoKeysSuccessfullyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American.
        /// </summary>
        public static string Lng_AmericanEnglish {
            get {
                return ResourceManager.GetString("Lng_AmericanEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Lng_BritishEnglish {
            get {
                return ResourceManager.GetString("Lng_BritishEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian French.
        /// </summary>
        public static string Lng_CanadianFrench {
            get {
                return ResourceManager.GetString("Lng_CanadianFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string Lng_Dutch {
            get {
                return ResourceManager.GetString("Lng_Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string Lng_French {
            get {
                return ResourceManager.GetString("Lng_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string Lng_German {
            get {
                return ResourceManager.GetString("Lng_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Lng_Italian {
            get {
                return ResourceManager.GetString("Lng_Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Lng_Japanese {
            get {
                return ResourceManager.GetString("Lng_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string Lng_Korean {
            get {
                return ResourceManager.GetString("Lng_Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin America.
        /// </summary>
        public static string Lng_LatinAmericanSpanish {
            get {
                return ResourceManager.GetString("Lng_LatinAmericanSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Lng_Portuguese {
            get {
                return ResourceManager.GetString("Lng_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Lng_Russian {
            get {
                return ResourceManager.GetString("Lng_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplified Chinese.
        /// </summary>
        public static string Lng_SimplifiedChinese {
            get {
                return ResourceManager.GetString("Lng_SimplifiedChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Lng_Spanish {
            get {
                return ResourceManager.GetString("Lng_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional Chinese.
        /// </summary>
        public static string Lng_TraditionalChinese {
            get {
                return ResourceManager.GetString("Lng_TraditionalChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Lng_Unknown {
            get {
                return ResourceManager.GetString("Lng_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localized Info.
        /// </summary>
        public static string LocalizedInfo {
            get {
                return ResourceManager.GetString("LocalizedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close File.
        /// </summary>
        public static string MenuItem_CloseFile {
            get {
                return ResourceManager.GetString("MenuItem_CloseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuItem_ExitApp {
            get {
                return ResourceManager.GetString("MenuItem_ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuItem_File {
            get {
                return ResourceManager.GetString("MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string MenuItem_OpenFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open last.
        /// </summary>
        public static string MenuItem_OpenLastFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenLastFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MenuItem_Options {
            get {
                return ResourceManager.GetString("MenuItem_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string MenuItem_Settings {
            get {
                return ResourceManager.GetString("MenuItem_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string Metadata {
            get {
                return ResourceManager.GetString("Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Type.
        /// </summary>
        public static string NcaContentType {
            get {
                return ResourceManager.GetString("NcaContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defined Sections.
        /// </summary>
        public static string NcaDefinedSections {
            get {
                return ResourceManager.GetString("NcaDefinedSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo Switch file (*.nsp)|*.nsp|All files (*.*)|*.*.
        /// </summary>
        public static string OpenFile_Filter {
            get {
                return ResourceManager.GetString("OpenFile_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file(s)....
        /// </summary>
        public static string SaveSelectedFiles {
            get {
                return ResourceManager.GetString("SaveSelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK Version.
        /// </summary>
        public static string SdkVersion {
            get {
                return ResourceManager.GetString("SdkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure.
        /// </summary>
        public static string Structure {
            get {
                return ResourceManager.GetString("Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title ID.
        /// </summary>
        public static string TitleId {
            get {
                return ResourceManager.GetString("TitleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string TitleVersion {
            get {
                return ResourceManager.GetString("TitleVersion", resourceCulture);
            }
        }
    }
}
